#### Modifying the entries of an Array:

In [3]:
import numpy as np
r_arr=np.random.randn(10)
r_arr

array([ 0.33606763,  0.50604654, -0.16965599,  1.24152307, -0.59439062,
       -0.94630727, -0.78128156,  0.87242161, -0.8703773 ,  0.32608222])

In [5]:
r_arr[3:5]

array([ 1.24152307, -0.59439062])

In [9]:
r_arr[3:5]=5
r_arr

array([ 0.33606763,  0.50604654, -0.16965599,  5.        ,  5.        ,
       -0.94630727, -0.78128156,  0.87242161, -0.8703773 ,  0.32608222])

In [11]:
#Using Conditional Operators
r_arr[r_arr>0]=65
r_arr

array([65.        , 65.        , -0.16965599, 65.        , 65.        ,
       -0.94630727, -0.78128156, 65.        , -0.8703773 , 65.        ])

#### Modifying matrix entries:

In [13]:
r_mat=np.random.randn(5,5)
r_mat

array([[ 0.0678149 , -0.95597168,  1.29585428, -1.09825941, -1.51951756],
       [ 1.5314087 , -1.77544629,  0.24008597, -0.05201493,  0.33295861],
       [ 0.18841048, -1.07135991,  2.11775234,  0.92028114, -0.31896568],
       [-0.38199692, -0.36609935,  0.82461411,  0.99952588, -1.87515869],
       [ 0.9213011 ,  0.46086007,  0.6208231 , -1.53410325, -0.11955657]])

In [15]:
r_mat[1:3,3:5]

array([[-0.05201493,  0.33295861],
       [ 0.92028114, -0.31896568]])

In [17]:
r_mat[1:3,3:5]=0
r_mat

array([[ 0.0678149 , -0.95597168,  1.29585428, -1.09825941, -1.51951756],
       [ 1.5314087 , -1.77544629,  0.24008597,  0.        ,  0.        ],
       [ 0.18841048, -1.07135991,  2.11775234,  0.        ,  0.        ],
       [-0.38199692, -0.36609935,  0.82461411,  0.99952588, -1.87515869],
       [ 0.9213011 ,  0.46086007,  0.6208231 , -1.53410325, -0.11955657]])

#### Extracting Sub Matrix:

In [19]:
r_mat=np.random.randn(5,5)
r_mat

array([[ 1.69110618, -1.18547833, -0.82956819,  1.51362626,  0.06333075],
       [ 0.19479929,  1.36239143, -0.10766189,  1.19267836,  1.70435053],
       [ 0.78515282, -1.34683462, -0.64298425, -0.14469498, -0.64419437],
       [-0.17081748, -0.58683114,  0.38959471, -1.71805495,  0.12769136],
       [ 0.07546269,  0.14443752, -0.33837318, -0.03996096,  0.46338412]])

In [21]:
#extract first 2 rows and first 3 columns
sub_mat=r_mat[0:2,0:3]
sub_mat

array([[ 1.69110618, -1.18547833, -0.82956819],
       [ 0.19479929,  1.36239143, -0.10766189]])

In [23]:
#changing all values of extracted matrix to 3
sub_mat[:]=3
sub_mat

array([[3., 3., 3.],
       [3., 3., 3.]])

In [25]:
r_mat

array([[ 3.        ,  3.        ,  3.        ,  1.51362626,  0.06333075],
       [ 3.        ,  3.        ,  3.        ,  1.19267836,  1.70435053],
       [ 0.78515282, -1.34683462, -0.64298425, -0.14469498, -0.64419437],
       [-0.17081748, -0.58683114,  0.38959471, -1.71805495,  0.12769136],
       [ 0.07546269,  0.14443752, -0.33837318, -0.03996096,  0.46338412]])

In [29]:
#To prevent this. we make a copy of array using .copy() function
r_mat=np.random.randn(5,5)
print(r_mat,"\n")
sub_mat=r_mat[0:2,0:3].copy()
print(sub_mat,"\n")
sub_mat[:]=3
print(sub_mat,"\n")
print(r_mat,"\n")

[[-0.17062931 -0.2131109   0.61604318  0.57571321 -0.5736451 ]
 [-0.15251616 -0.05758903 -1.44294849 -0.52018385 -0.61204934]
 [ 0.88403746  1.45920659 -0.3653071  -0.80561101 -0.36503424]
 [-1.01388551  0.69755423 -0.06209822  0.53672134  0.42177586]
 [-1.6307196  -0.37877639 -0.02541282 -1.21367234 -1.0720727 ]] 

[[-0.17062931 -0.2131109   0.61604318]
 [-0.15251616 -0.05758903 -1.44294849]] 

[[3. 3. 3.]
 [3. 3. 3.]] 

[[-0.17062931 -0.2131109   0.61604318  0.57571321 -0.5736451 ]
 [-0.15251616 -0.05758903 -1.44294849 -0.52018385 -0.61204934]
 [ 0.88403746  1.45920659 -0.3653071  -0.80561101 -0.36503424]
 [-1.01388551  0.69755423 -0.06209822  0.53672134  0.42177586]
 [-1.6307196  -0.37877639 -0.02541282 -1.21367234 -1.0720727 ]] 



# Saving and Loading In Numpy:

In [33]:
#Creating a random matrix
r_mat1=np.random.randint(1,10,10).reshape(2,5)
print(r_mat1)
print("")
r_mat2=np.random.randint(1,10,10).reshape(2,5)
print(r_mat2)

[[5 3 8 3 9]
 [6 3 6 3 8]]

[[9 2 9 2 2]
 [8 2 2 4 8]]


#### Using np.save() function

In [35]:
import os
os.getcwd()

'C:\\Users\\Administrator'

In [37]:
np.save("numpymat1",r_mat1)

#### Using np.savez() function:

In [42]:
np.savez("multiplefile",r_mat1=r_mat1,r_mat2=r_mat2)

In [45]:
loadarr=np.load("numpymat1.npy")
print(loadarr)
print("")
loadarr2=np.load("multiplefile.npz")
print(loadarr2)

[[5 3 8 3 9]
 [6 3 6 3 8]]



In [47]:
#npz file returns the address of memory location.

In [49]:
loadarr2["r_mat1"]

array([[5, 3, 8, 3, 9],
       [6, 3, 6, 3, 8]])

In [50]:
loadarr2["r_mat2"]

array([[9, 2, 9, 2, 2],
       [8, 2, 2, 4, 8]])