# Numpy

In [2]:
import numpy as np

In [4]:
str_ar=["mercedes",6,"Audi","Ferrari","Tesla"]
num_ar=[5,1,2,3,4,5]

In [6]:
print(str_ar)
print(num_ar)

['mercedes', 6, 'Audi', 'Ferrari', 'Tesla']
[5, 1, 2, 3, 4, 5]


In [9]:
np_strar=np.array(str_ar)
np_numar=np.array(num_ar)

In [12]:
print(np_strar)
print(np_numar)

['mercedes' '6' 'Audi' 'Ferrari' 'Tesla']
[5 1 2 3 4 5]


In [14]:
type(np_strar)

numpy.ndarray

In [17]:
#MATRIX
matrix1=np.array([[1,2,1],[4,5,9],[1,8,9]])
matrix1

array([[1, 2, 1],
       [4, 5, 9],
       [1, 8, 9]])

In [19]:
matrix1.shape


(3, 3)

# Numpy Functions

#### 1: np.arange()

In [24]:
arr2=np.arange(0,10)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
arr2=np.arange(0,10,2)
print(arr2)

[0 2 4 6 8]


#### 2: np.linspace()

In [29]:
matrix2=np.linspace(0,10)
matrix2

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [32]:
matrix3=np.linspace(11,20,10)
matrix3

array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

#### 3: np.zeros()

In [34]:
matrix4=np.zeros([5,3])
matrix4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### 4: np.ones()

In [37]:
matrix5=np.ones([3,5])
matrix5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### 5: np.eye()

In [41]:
matrix6=np.eye(5)
matrix6

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])