In [ ]:
import numpy as np

In [ ]:
arr4=np.arange(10)
arr4

##### 6: np.reshape() method

In [10]:
arr4_reshape=arr4.reshape((5,2))
arr4_reshape

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [12]:
arr4_reshape.shape

(5, 2)

In [13]:
#Error because of lacking elements in an array
arr4_reshape((10,2))

TypeError: 'numpy.ndarray' object is not callable

### Operations on array:-

In [26]:
list1=[1,2,3]  #concatenation of list
list2=[4,5,6]
print(list1+list2)

[1, 2, 3, 4, 5, 6]


In [18]:
np.array(list1)+np.array(list2)

array([5, 7, 9])

In [21]:
print(list1*3)
print(np.array(list1)*3)

[1, 2, 3, 1, 2, 3, 1, 2, 3]
[3 6 9]


In [24]:
arr7= np.array([1,2,3,4,5])
arr8= np.array([7,8,9,10,11])
print(arr7+arr8)
print(arr7-arr8)
print(arr7*arr8)
print(1/arr8) #Inverse
print(arr7-arr8)

[ 8 10 12 14 16]
[-6 -6 -6 -6 -6]
[ 7 16 27 40 55]
[0.14285714 0.125      0.11111111 0.1        0.09090909]
[-6 -6 -6 -6 -6]


#### Operations on Matrices:-

In [28]:
matrix7=np.arange(1,10).reshape(3,3)
print(matrix7)
matrix8=np.eye(3)
print(matrix8)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
print("Add: \n",matrix7+matrix8)
print("Sub: \n",matrix7-matrix8)
print("Multiply: \n",matrix7*matrix8)
print("Divide: ",matrix7/matrix8)

Add: 
 [[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
Sub: 
 [[0. 2. 3.]
 [4. 4. 6.]
 [7. 8. 8.]]
Multiply: 
 [[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]
Divide:  [[ 1. inf inf]
 [inf  5. inf]
 [inf inf  9.]]


C:\Users\STUDENT\AppData\Local\Temp\ipykernel_1900\1663195754.py:4: RuntimeWarning: divide by zero encountered in true_divide
  print("Divide: ",matrix7/matrix8)


In [33]:
matrix7 @ matrix8  #Dot Multiplication

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [35]:
np.transpose(matrix7)  #transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [37]:
matrix7.T   #transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

#### Min and max in Matrix

In [39]:
np.min(matrix7)

1

In [41]:
np.max(matrix7)

9

#### Function to generate random samples:

In [43]:
rand_mat=np.random.rand(5) #IN ARRAYS
print(rand_mat)

[0.68095422 0.73535916 0.7586863  0.44478664 0.3566435 ]


In [45]:
rand_mat=np.random.rand(5,5) #IN MATRIX
print(rand_mat)

[[0.73912734 0.28222182 0.55847131 0.41652438 0.04972252]
 [0.26609153 0.03391975 0.28329034 0.91817852 0.00548396]
 [0.71287703 0.35215337 0.9917019  0.32600735 0.7595425 ]
 [0.57347611 0.15393232 0.99898604 0.40651006 0.75085608]
 [0.41976533 0.18470859 0.34781355 0.59087032 0.48779031]]


In [55]:
rand_2=np.random.randn(100) #Mean = 0 and S.D=1
rand_2


array([ 0.90082142,  0.19340349, -1.28735515, -0.80977881,  0.5109287 ,
        0.49368431,  0.01804808,  0.20311004, -0.69561877,  0.59066638,
        0.08582479, -0.47136879,  1.7437147 , -0.72954168, -0.67647838,
       -1.05199002, -0.6256809 ,  0.29353258, -0.86659369,  0.36272467,
       -0.57050196,  0.96788145, -0.82377865, -0.77490033,  1.39291489,
        0.39151063,  0.40307359,  1.22978222,  1.09646842,  1.27599399,
        0.79375494,  0.727692  ,  0.49880462,  0.06537291,  1.10631686,
       -0.51132939, -0.55297794, -0.38235595,  0.67346972, -0.13394443,
        0.20130893,  0.59442194, -0.29196283,  0.55300455, -0.0666195 ,
        0.59095784, -0.73072333, -0.03157701,  0.13981303,  0.59167878,
        0.51547152,  0.69068472, -0.5832056 ,  0.35916711, -0.70276951,
        0.23333673,  1.294678  ,  0.0716176 ,  2.3047842 ,  1.06684147,
        1.6398726 ,  1.41953922, -0.71290474,  0.27439405,  0.32559133,
        0.22315671, -1.37132245,  0.20133973, -1.58703613,  0.16

In [56]:
np.mean(rand_2)

0.126549166397209

In [58]:
np.std(rand_2)

0.8401318420296918

# randint() :

In [63]:
rand_3=np.random.randint(2,6,10) #IN ARRAY
rand_3  # 2 included and 6 excluded

array([3, 3, 5, 2, 5, 3, 4, 5, 4, 2])

In [66]:
rand_4=np.random.randint(1,10,[3,5])
print(rand_4)

[[2 5 4 6 5]
 [4 3 2 1 4]
 [6 7 8 8 4]]


## Accessing the entries of a Numpy Array:-

In [68]:
rand_arr=np.random.randn(10)
rand_arr

array([-0.77593598,  1.51412763, -2.18928772,  0.26889444, -0.26957126,
        0.73813399,  1.16315123,  0.68453537, -0.99619104, -0.30525089])

In [70]:
rand_arr[5]

0.738133991883783

In [72]:
rand_arr[2:6]

array([-2.18928772,  0.26889444, -0.26957126,  0.73813399])

In [77]:
#we can also access multiple non-consecutive entries using np.range
print("Index of values to access: ",np.arange(3,10,3))
print(rand_arr[np.arange(3,10,3)])

Index of values to access:  [3 6 9]
[ 0.26889444  1.16315123 -0.30525089]


#### Accessing using Logical Operators!!!!

In [79]:
rand_arr>0

array([False,  True, False,  True, False,  True,  True,  True, False,
       False])

In [81]:
rand_arr[rand_arr>0]

array([1.51412763, 0.26889444, 0.73813399, 1.16315123, 0.68453537])

# Accessing in Matrices:-

In [84]:
rand_mat=np.random.randn(5,5)
rand_mat

array([[ 0.37555684, -1.33150701,  0.47724859,  1.25231051, -0.15883116],
       [-1.02484982, -0.593881  ,  0.87521783, -0.02482194, -0.19625388],
       [ 2.57991771, -1.19549581, -0.73959178,  0.17297907,  0.10587321],
       [-1.60070276,  1.07510438, -0.07928606, -0.45509335, -0.14028964],
       [-1.70816976,  0.57193066,  0.79426423,  0.97255449, -0.29460786]])

In [86]:
rand_mat[1]

array([-1.02484982, -0.593881  ,  0.87521783, -0.02482194, -0.19625388])

In [91]:
rand_mat[0][2]

0.4772485908126146

In [93]:
rand_mat[0,2]

0.4772485908126146

In [95]:
#accessing first two rows with second and third column
rand_mat[0:2,1:3]

array([[-1.33150701,  0.47724859],
       [-0.593881  ,  0.87521783]])

#### Accessing matrices using logical operations:- 

In [97]:
print(rand_mat)

[[ 0.37555684 -1.33150701  0.47724859  1.25231051 -0.15883116]
 [-1.02484982 -0.593881    0.87521783 -0.02482194 -0.19625388]
 [ 2.57991771 -1.19549581 -0.73959178  0.17297907  0.10587321]
 [-1.60070276  1.07510438 -0.07928606 -0.45509335 -0.14028964]
 [-1.70816976  0.57193066  0.79426423  0.97255449 -0.29460786]]


In [99]:
rand_mat[rand_mat>0]

array([0.37555684, 0.47724859, 1.25231051, 0.87521783, 2.57991771,
       0.17297907, 0.10587321, 1.07510438, 0.57193066, 0.79426423,
       0.97255449])

In [100]:
rand_mat[rand_mat<0]

array([-1.33150701, -0.15883116, -1.02484982, -0.593881  , -0.02482194,
       -0.19625388, -1.19549581, -0.73959178, -1.60070276, -0.07928606,
       -0.45509335, -0.14028964, -1.70816976, -0.29460786])